### ISSUE TITLE
Python 3 ZeroDivisionError

### ISSUE THREAD

**Issue by zenith-matic** [cataska/programming-collective-intelligence-code#5]
In Python 3 the code throws ZeroDivisionError:

"Traceback (most recent call last):
  File "/home/testing_out.py", line 4, in <module>
    clust = hierarchy_cluster(data)
  File "/home/clusters.py", line 74, in hierarchy_cluster
    closest = distance(cluster[0].vec, cluster[1].vec)
  File "/home/clusters.py", line 38, in pearson
    num = p_sum - (sum1 * sum2 / len(v1))
ZeroDivisionError: division by zero"

**Comment by zenith-matic** [comment]
Problem Solved by adding the float to the line: "num=pSum-(sum1*sum2/float(len(v1)))"
